### ISSUE TITLE
Bash Profile error after running example playbook

### ISSUE THREAD

**Issue by Luiggi33** [MVladislav/ansible-cis-ubuntu-2404#5]
### Describe the problem

After running the playbook, when the bash profile is loaded an error gets printed into the console

### Expected behavior

The input should be clean

### What is version of application which has the issue?

commit 14e7c75c61ec0a62fc5d8461292b798a2761fa57

### What type of installation are you running?

OS (setup.py)

### What type of device you use to interact with the application?

OS: [e.g. linux, windows, ios]

### Anything in the logs that might be useful for us?

```txt
-bash: TMOUT: readonly variable
-bash: TMOUT: readonly variable
```

### Additional information

Should be related to https://github.com/MVladislav/ansible-cis-ubuntu-2404/blob/acadfba7427ff14a6c0e299daae336b99af417a6/tasks/section5.yml#L1704-L1724

**Comment by MVladislav** [comment]
You're right; it's not directly an error, but since the entry was duplicated, it caused the variable to be set multiple times, leading to the output you saw. I've update the duplicated lines and ensured the variable is set only once.

This update has been applied to both '5.4.3.2' and '5.4.3.3'.

**Comment by Luiggi33** [comment]
Running the example playbook after efdca87c5cdd84524321265533121a207c41e9fe does not produce the issue anymore. Thanks for the fast fix
